const API="https://placementportal-production-733c.up.railway.app/api";
let token=localStorage.getItem("pp_token");
let currentUser=JSON.parse(localStorage.getItem("pp_user")||"null");
const app=document.getElementById("app"), nav=document.getElementById("nav"), navActions=document.getElementById("navActions");

function toast(msg, ok=true){const t=document.getElementById("toast");t.textContent=msg;t.className=ok?"toast ok":"toast bad";setTimeout(()=>t.className="",2800)}
async function api(url,options={}){options.headers={"Content-Type":"application/json",...(options.headers||{})};if(token)options.headers.Authorization="Bearer "+token;const r=await fetch(API+url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function validateEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function validatePassword(value){return typeof value === "string" && value.length >= 6}
function validateFormValues({email,password,name}={}){
  if(email && !validateEmail(email)) throw new Error("Please enter a valid email address");
  if(password && !validatePassword(password)) throw new Error("Password must contain at least 6 characters");
  if(name && name.trim().length < 2) throw new Error("Name must contain at least 2 characters");
}
function showPage(page){location.hash=page;render()}
function logout(){token=null;currentUser=null;localStorage.clear();showPage("home");toast("Logged out")}
function shellNav(){
  nav.innerHTML=`<a onclick="showPage('home')">Home</a><a onclick="showPage('jobs')">Jobs</a><a onclick="showPage('companies')">Companies</a><a onclick="showPage('about')">About</a>`;
  if(currentUser){navActions.innerHTML=`<button class="btn secondary" onclick="showPage('dashboard')">Dashboard</button><button class="btn outline" onclick="logout()">Logout</button>`}
  else navActions.innerHTML=`<button class="btn outline" onclick="showPage('login')">Login</button><button class="btn primary" onclick="showPage('register')">Register</button>`;
}
function render(){shellNav();const p=location.hash.slice(1)||"home";const pages={home,login,register,jobs,companies,about,dashboard};(pages[p]||home)();}

async function home(){
 app.innerHTML=`<section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Smart Campus Recruitment</div><h1>Connect talent with opportunity.</h1><p>A modern placement portal for students, companies and placement officers. Discover jobs, manage applications and track campus placements in one place.</p><div style="display:flex;gap:10px;margin-top:25px"><button class="btn primary" onclick="showPage('jobs')">Explore Jobs →</button><button class="btn" style="background:white;color:#172033" onclick="showPage('register')">Create Account</button></div></div><div class="hero-card"><h3 style="margin-top:0">Placement snapshot</h3><div class="mini"><span>Active opportunities</span><b>Live</b></div><div class="mini"><span>Student applications</span><b>Tracked</b></div><div class="mini"><span>Recruiter workspace</span><b>Ready</b></div><div class="mini"><span>Placement analytics</span><b>Built-in</b></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><h2>Everything in one portal</h2><p class="muted">A simple workflow for the complete recruitment lifecycle.</p></div></div><div class="stats"><div class="stat"><b>01</b><span>Build profile</span><p class="muted">Students maintain skills, CGPA and resume details.</p></div><div class="stat"><b>02</b><span>Find opportunities</span><p class="muted">Browse openings and eligibility requirements.</p></div><div class="stat"><b>03</b><span>Apply online</span><p class="muted">Submit applications and monitor their status.</p></div><div class="stat"><b>04</b><span>Hire & track</span><p class="muted">Companies shortlist candidates and update outcomes.</p></div></div></div></section>
<section class="section" style="padding-top:0"><div class="container"><div class="section-head"><div><h2>Latest opportunities</h2><p class="muted">Explore current openings.</p></div><button class="btn secondary" onclick="showPage('jobs')">View all</button></div><div id="homeJobs" class="job-grid"><div class="empty">Loading jobs...</div></div></div></section>`;
  try{const jobs=await api("/jobs");document.getElementById("homeJobs").innerHTML=jobs.slice(0,3).map(jobCard).join("")||`<div class="empty">No jobs posted yet.</div>`}catch(e){document.getElementById("homeJobs").innerHTML=`<div class="empty">Connect the database to show live jobs.</div>`}
}
function jobCard(j){return `<div class="job-card"><span class="tag">${esc(j.industry||"Recruitment")}</span><h3>${esc(j.title)}</h3><div class="company-row"><div class="company-logo">${esc((j.company_name||"C").slice(0,1).toUpperCase())}</div><div><b>${esc(j.company_name)}</b><div class="muted">${esc(j.location||"Campus")}</div></div></div><div class="job-meta"><span>💼 ${Number(j.package_lpa).toFixed(1)} LPA</span><span>🎓 ${esc(j.eligible_department||"All")} · Min CGPA ${Number(j.min_cgpa).toFixed(1)}</span><span>📅 Deadline: ${esc(j.deadline||"Not specified")}</span></div><button class="btn primary" style="width:100%" onclick="openJob(${j.id})">View opportunity</button></div>`}
async function jobs(){
 app.innerHTML=`<section class="section"><div class="container"><div class="section-head"><div><h2>Job Opportunities</h2><p class="muted">Search and explore campus recruitment openings.</p></div></div><div class="toolbar"><input id="jobSearch" class="input" placeholder="Search by role, company or location"><button class="btn primary" onclick="loadJobs()">Search</button></div><div id="jobsList" class="job-grid"><div class="empty">Loading...</div></div></div></section>`;
 loadJobs();
}
async function loadJobs(){try{const q=document.getElementById("jobSearch")?.value||"";const rows=await api("/jobs?q="+encodeURIComponent(q));document.getElementById("jobsList").innerHTML=rows.map(jobCard).join("")||`<div class="empty">No matching jobs.</div>`}catch(e){toast(e.message,false)}}
async function openJob(id){try{const rows=await api("/jobs");const j=rows.find(x=>x.id==id);if(!j)return;app.insertAdjacentHTML("beforeend",`<div class="modal" id="jobModal"><div class="modal-box"><button class="btn outline" style="float:right" onclick="document.getElementById('jobModal').remove()">Close</button><span class="tag">${esc(j.industry)}</span><h2>${esc(j.title)}</h2><h3>${esc(j.company_name)}</h3><p>${esc(j.description||"No description provided.")}</p><div class="two-col"><div><b>Package</b><p>${Number(j.package_lpa).toFixed(1)} LPA</p></div><div><b>Location</b><p>${esc(j.location||"Not specified")}</p></div><div><b>Eligibility</b><p>${esc(j.eligible_department)} · CGPA ${Number(j.min_cgpa).toFixed(1)}+</p></div><div><b>Deadline</b><p>${esc(j.deadline||"Not specified")}</p></div></div>${currentUser?.role==="student"?`<button class="btn primary" onclick="applyJob(${j.id})">Apply Now</button>`:`<button class="btn primary" onclick="showPage('login')">Login to apply</button>`}</div></div>`)}catch(e){toast(e.message,false)}}
async function applyJob(id){try{const r=await api(`/jobs/${id}/apply`,{method:"POST"});toast(r.message);document.getElementById("jobModal")?.remove()}catch(e){toast(e.message,false)}}

function login(){app.innerHTML=`<div class="auth-wrap"><div class="auth"><h1>Welcome back</h1><p class="muted">Sign in to your placement workspace.</p><form class="form" onsubmit="doLogin(event)"><div><label class="label">Email</label><input id="email" class="input" type="email" required placeholder="you@example.com"></div><div><label class="label">Password</label><input id="password" class="input" type="password" required placeholder="••••••••"></div><button class="btn primary">Login</button></form><div class="notice"><b>Demo accounts</b><br>Admin: admin@placement.edu / admin123<br>Student: student@placement.edu / student123<br>Company: hr@techcorp.com / company123</div><p class="muted">New user? <a href="#register">Create an account</a></p></div></div>`}
async function doLogin(e){e.preventDefault();try{validateFormValues({email:email.value.trim(),password:password.value});const r=await api("/auth/login",{method:"POST",body:JSON.stringify({email:email.value.trim(),password:password.value})});token=r.token;currentUser=r.user;localStorage.setItem("pp_token",token);localStorage.setItem("pp_user",JSON.stringify(currentUser));toast("Login successful");showPage("dashboard")}catch(x){toast(x.message,false)}}

function register(){app.innerHTML=`<div class="auth-wrap"><div class="auth" style="width:min(680px,94%)"><h1>Create your account</h1><p class="muted">Register as a student or recruiter.</p><form class="form" onsubmit="doRegister(event)"><div class="form-grid"><div><label class="label">Full name</label><input id="rname" class="input" required></div><div><label class="label">Email</label><input id="remail" class="input" type="email" required></div></div><div class="form-grid"><div><label class="label">Password</label><input id="rpass" class="input" type="password" minlength="6" required></div><div><label class="label">Account type</label><select id="rrole" class="input" onchange="toggleRegisterFields()"><option value="student">Student</option><option value="company">Company</option></select></div></div><div id="studentFields" class="form-grid"><div><label class="label">Roll number</label><input id="rollNo" class="input"></div><div><label class="label">Department</label><input id="department" class="input" placeholder="CSE / CSM / ECE"></div><div><label class="label">CGPA</label><input id="cgpa" class="input" type="number" min="0" max="10" step=".01"></div><div><label class="label">Graduation year</label><input id="grad" class="input" type="number" value="2027"></div></div><div id="companyFields" class="form-grid hidden"><div><label class="label">Company name</label><input id="companyName" class="input"></div><div><label class="label">Industry</label><input id="industry" class="input"></div><div><label class="label">Location</label><input id="location" class="input"></div><div><label class="label">Website</label><input id="website" class="input"></div></div><div><label class="label">Skills <span class="muted">(students)</span></label><input id="skills" class="input" placeholder="JavaScript, Java, SQL"></div><button class="btn primary">Create Account</button></form></div></div>`}
function toggleRegisterFields(){const company=rrole.value==="company";studentFields.classList.toggle("hidden",company);companyFields.classList.toggle("hidden",!company)}
async function doRegister(e){e.preventDefault();try{validateFormValues({name:rname.value,email:remail.value.trim(),password:rpass.value});}catch(x){toast(x.message,false);return}const company=rrole.value==="company";const body={name:rname.value,email:remail.value,password:rpass.value,role:rrole.value,rollNo:rollNo?.value,department:department?.value,cgpa:cgpa?.value,graduationYear:grad?.value,skills:skills?.value,companyName:companyName?.value,industry:industry?.value,location:location?.value,website:website?.value};try{const r=await api("/auth/register",{method:"POST",body:JSON.stringify(body)});toast(r.message);showPage("login")}catch(x){toast(x.message,false)}}

async function companies(){app.innerHTML=`<section class="section"><div class="container"><h2>Recruiting Companies</h2><p class="muted">Companies participating in campus recruitment.</p><div id="companiesList" class="job-grid" style="margin-top:25px"><div class="empty">Loading...</div></div></div></section>`;try{const jobs=await api("/jobs");const map={};jobs.forEach(j=>{if(!map[j.company_name])map[j.company_name]=j});document.getElementById("companiesList").innerHTML=Object.values(map).map(j=>`<div class="card"><div class="company-row"><div class="company-logo">${esc(j.company_name.slice(0,1))}</div><div><h3 style="margin:0">${esc(j.company_name)}</h3><p class="muted">${esc(j.industry||"Technology")} · ${esc(j.company_location||j.location||"")}</p></div></div><p>${esc(j.title)} opportunity available.</p><button class="btn secondary" onclick="showPage('jobs')">View openings</button></div>`).join("")||`<div class="empty">Companies will appear when jobs are posted.</div>`}catch(e){toast(e.message,false)}}
function about(){app.innerHTML=`<section class="section"><div class="container"><div class="card"><h2>About CampusHire</h2><p class="muted" style="line-height:1.8">CampusHire is a prototype placement management portal designed to connect students, recruiters and the college placement cell. It supports job discovery, eligibility checks, online applications, candidate shortlisting and placement analytics.</p><div class="row g-4 mt-1"><div class="col-12 col-md-6"><div class="card h-100"><h3>Student workflow</h3><p>Register → Complete profile → Find eligible jobs → Apply → Track status.</p></div></div><div class="col-12 col-md-6"><div class="card h-100"><h3>Recruiter workflow</h3><p>Register → Post opening → Review applicants → Shortlist → Update outcome.</p></div></div></div></div></div></section>`}

async function dashboard(){if(!currentUser){showPage("login");return}if(currentUser.role==="student")studentDash();else if(currentUser.role==="company")companyDash();else adminDash()}
async function studentDash(){app.innerHTML=`<section class="dashboard"><div class="container"><div class="dashboard-head"><div><h2>Student Dashboard</h2><p class="muted">Welcome, ${esc(currentUser.name)}.</p></div><button class="btn primary" onclick="showPage('jobs')">Find Jobs</button></div><div class="two-col"><div class="card" id="profileCard">Loading profile...</div><div class="card"><h3>My Applications</h3><div id="myApps">Loading...</div></div></div></div></section>`;try{const p=await api("/profile");profileCard.innerHTML=`<h3>My Profile</h3><form class="form" onsubmit="saveProfile(event)"><div class="form-grid"><div><label class="label">Name</label><input id="pname" class="input" value="${esc(p.name)}"></div><div><label class="label">Roll No</label><input id="proll" class="input" value="${esc(p.roll_no)}"></div><div><label class="label">Department</label><input id="pdept" class="input" value="${esc(p.department)}"></div><div><label class="label">CGPA</label><input id="pcgpa" class="input" type="number" step=".01" value="${p.cgpa}"></div></div><div><label class="label">Skills</label><input id="pskills" class="input" value="${esc(p.skills)}"></div><div><label class="label">Resume filename/link</label><input id="presume" class="input" value="${esc(p.resume||"")}"></div><button class="btn primary">Save Profile</button></form>`;const a=await api("/applications/me");myApps.innerHTML=a.length?`<div style="display:grid;gap:10px">${a.map(x=>`<div class="notice"><b>${esc(x.title)}</b> · ${esc(x.company_name)}<br><span class="pill ${x.status==="Selected"?"success":x.status==="Rejected"?"error":"warning"}">${esc(x.status)}</span></div>`).join("")}</div>`:`<div class="empty">No applications yet.</div>`}catch(e){toast(e.message,false)}}
async function saveProfile(e){e.preventDefault();try{const r=await api("/students/profile",{method:"PUT",body:JSON.stringify({name:pname.value,rollNo:proll.value,department:pdept.value,cgpa:pcgpa.value,graduationYear:2027,skills:pskills.value,resume:presume.value})});toast(r.message);currentUser.name=pname.value;localStorage.setItem("pp_user",JSON.stringify(currentUser));}catch(x){toast(x.message,false)}}

async function companyDash(){app.innerHTML=`<section class="dashboard"><div class="container"><div class="dashboard-head"><div><h2>Recruiter Dashboard</h2><p class="muted">Manage your openings and applicants.</p></div><button class="btn primary" onclick="showPostJob()">+ Post Job</button></div><div class="two-col"><div class="card"><h3>Post a new opening</h3><div id="postForm" class="empty">Click “Post Job” to create an opening.</div></div><div class="card"><h3>Applicant pipeline</h3><div id="applicants">Loading...</div></div></div></div></section>`;try{const a=await api("/company/applicants");document.getElementById("applicants").innerHTML=a.length?a.map(x=>`<div class="notice"><b>${esc(x.name)}</b> · ${esc(x.title)}<br>${esc(x.department)} · CGPA ${x.cgpa}<br><select class="input" style="margin-top:8px" onchange="updateStatus(${x.application_id},this.value)">${["Applied","Shortlisted","Interview","Selected","Rejected"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></div>`).join(""):`<div class="empty">No applicants yet.</div>`}catch(e){toast(e.message,false)}}
function showPostJob(){postForm.innerHTML=`<form class="form" onsubmit="postJob(event)"><input id="jtitle" class="input" placeholder="Job title" required><textarea id="jdesc" class="input" rows="4" placeholder="Job description"></textarea><div class="form-grid"><input id="jpack" class="input" type="number" step=".1" placeholder="Package (LPA)" required><input id="jloc" class="input" placeholder="Location"></div><div class="form-grid"><input id="jcgpa" class="input" type="number" step=".1" min="0" max="10" placeholder="Minimum CGPA"><input id="jdept" class="input" placeholder="Department or All" value="All"></div><input id="jdate" class="input" type="date"><button class="btn primary">Publish Job</button></form>`}
async function postJob(e){e.preventDefault();if(Number(jpack.value)<0||Number(jcgpa.value)<0||Number(jcgpa.value)>10){toast("Enter valid package and CGPA values",false);return}try{const r=await api("/jobs",{method:"POST",body:JSON.stringify({title:jtitle.value,description:jdesc.value,packageLpa:jpack.value,location:jloc.value,minCgpa:jcgpa.value,eligibleDepartment:jdept.value,deadline:jdate.value})});toast(r.message);companyDash()}catch(x){toast(x.message,false)}}
async function updateStatus(id,status){try{const r=await api(`/applications/${id}/status`,{method:"PUT",body:JSON.stringify({status})});toast(r.message)}catch(e){toast(e.message,false)}}

async function adminDash(){app.innerHTML=`<section class="dashboard"><div class="container"><div class="dashboard-head"><div><h2>Placement Officer Dashboard</h2><p class="muted">Monitor the placement ecosystem.</p></div></div><div id="adminStats" class="dash-grid">Loading...</div><div class="card"><h3>Registered Users</h3><div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th></tr></thead><tbody id="users"></tbody></table></div></div></div></section>`;try{const s=await api("/admin/stats");adminStats.innerHTML=[["Students",s.students],["Companies",s.companies],["Open Jobs",s.jobs],["Applications",s.applications],["Selected",s.selected],["Avg Package",s.avgPackage+" LPA"],["Highest Package",s.highestPackage+" LPA"]].map(x=>`<div class="stat"><b>${esc(x[1])}</b><span>${esc(x[0])}</span></div>`).join("");const u=await api("/admin/users");users.innerHTML=u.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td><span class="pill">${esc(x.role)}</span></td><td>${new Date(x.created_at).toLocaleDateString()}</td></tr>`).join("")}catch(e){toast(e.message,false)}}
render();
